version: '3.7'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: measure
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db